apiVersion: apps/v1
kind: Deployment
metadata:
  name: djwebapp
  namespace: default
  labels:
    app: djwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: djwebapp
  template:
    metadata:
      labels:
        app: djwebapp
    spec:
      containers:
      - name: djwebapp
        image: hoquenazmul/hello_dj:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: myconfigmapv1.0