apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.appName }}-service'
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.appName }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.appPort }}
