apiVersion: v1
kind: Service
metadata:
  name: djwebapp-service
  namespace: default
  labels:
    app: djwebapp
spec:
  type: NodePort
  selector:
    app: djwebapp
  ports:
  - name: http
    protocol: TCP
    port: 8000